### ISSUE TITLE
Mobile-token rullet ut til alle brukere (fase 2)

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/kundevendt#25]
Mål: 
- Avvikle bruk av papir-QRkoder i appen
- Oppnå at de fleste billettkjøp skjer i innlogget tilstand. 

Hensikt:
- Risiko/mye støy i fht. forelenge med WTW.
- Inntektssikring for AtB.
- Øke kundetilfredshet ved å tilby flere billettprodukter i appen.  
- OOS-partnere har en forventning om at vi løser dette.

### Features:

**Fase 2:**
Full rulle med token toggle, til folk flest. (Vurdere å gå ut til en mindre brukermasse for å validere konseptet "reisebevis")

- [ ] https://github.com/AtB-AS/mittatb-app/issues/1398 **Design klart, kan påstartes**
- [ ] https://github.com/AtB-AS/mittatb-app/issues/1588 **Design klart i _app_, kan påstartes**
- [ ] https://github.com/AtB-AS/mittatb-app/issues/1089 **Design klart, kan påstartes**
- [ ] https://github.com/AtB-AS/mittatb-app/issues/1086 **Design klart, kan påstartes**
- [ ] Brukertest reisebevis
	- Ikke prototype i Figma, men reell app kjørende fra staging. Folk inviteres på huset og kan bruke en av våre telefoner 
- [ ] Bruker-merging (innlogging med e-post eller tlf). Avhengighet/koordinering med plattform-team
- [ ] Utrede teknisk e-post innlogging @rosvik 
- [ ] https://github.com/AtB-AS/mittatb-app/issues/1587 @hildeor 
- [ ] https://github.com/AtB-AS/mittatb-app/issues/1088 Onboardingsekvens for å informere rundt reisebevis (lagre unna at du har vært igjennom onboarding?)
- [x] Avsjekke om QR-kode skal på egen fane i forhold til reisebevis @hildeor 
- [ ] Avhengig av å koordinere med Marked ang. reisebevis-kampanje
